;; -*- mode: eask; lexical-binding: t -*-

(package "ox-json"
         "0.4.0"
         "JSON export backend for Org mode")

(website-url "https://github.com/jlumpe/ox-json")
(keywords "outlines")

(package-file "ox-json.el")

(source "gnu")
(source "melpa")
(source "jcs-elpa")

(depends-on "emacs" "27.1")
(depends-on "org" "9.4")
(depends-on "s" "1.12")

(development
 (depends-on "package-lint")
 (depends-on "undercover"))
